<a href="https://colab.research.google.com/github/dk0893/experiment/blob/main/matplotlib_animation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%matplotlib notebook
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import animation, rc

In [3]:
def set_figure( ax, xs, ys ):
    #ax.clear()
    ax.tick_params(labelbottom=False, labelleft=False, labelright=False, labeltop=False)
    ax.set_xticks(range(xs))
    ax.set_yticks(range(ys))
    ax.set_xlim(0, xs)
    ax.set_ylim(0, ys)
    ax.grid(True)

In [4]:
color_list = ['red', 'white', 'green']
cmap = matplotlib.colors.LinearSegmentedColormap.from_list( 'colormap_name', color_list )

fig = plt.figure( figsize=(6, 4) )
ax = fig.add_subplot( 111 )
#fig, ax = plt.subplots() # こっちでもいい

artists = []
np_seq = np.arange(6).reshape(2, 3)
lst_value = [np_seq, np_seq / 6, np.flipud(np_seq)]
lst_vmin  = [None, None, None]
lst_vmax  = [None, None, None]
lst_text  = ["0: np_seq", "1: np_seq / 6", "2: np.flipud(np_seq)"]

for val, txt, vmin, vmax in zip(lst_value, lst_text, lst_vmin, lst_vmax):
  #ax = fig.add_subplot(111)
  set_figure( ax, 3, 2 )

  print( val )

  art_mesh = ax.pcolormesh( val, cmap=cmap, vmin=vmin, vmax=vmax )
  art_text = ax.text( 0, 2.1, txt )
  artists.append( [art_mesh, art_text] )

<IPython.core.display.Javascript object>

[[0 1 2]
 [3 4 5]]
[[0.         0.16666667 0.33333333]
 [0.5        0.66666667 0.83333333]]
[[3 4 5]
 [0 1 2]]


In [5]:
print( artists )

[[<matplotlib.collections.QuadMesh object at 0x7a589c8501c0>, Text(0, 2.1, '0: np_seq')], [<matplotlib.collections.QuadMesh object at 0x7a589c851060>, Text(0, 2.1, '1: np_seq / 6')], [<matplotlib.collections.QuadMesh object at 0x7a589c851570>, Text(0, 2.1, '2: np.flipud(np_seq)')]]


In [7]:
anim = animation.ArtistAnimation( fig, artists, interval=2000, repeat_delay=1000 )
anim.save( "anim.gif" )

# Google Colaboratoryの場合必要
rc('animation', html='jshtml')
#plt.close()
anim

In [8]:
!ls -l

total 20
-rw-r--r-- 1 root root 13918 Mar 12 11:46 anim.gif
drwxr-xr-x 1 root root  4096 Mar  8 14:25 sample_data


In [9]:
!mv ./anim.gif drive/MyDrive/Colab/

In [10]:
!ls -l drive/MyDrive/Colab/

total 85
-rw-------+ 1 root root 13918 Mar 12 11:46 anim.gif
-rw-------  1 root root 72066 Mar 12 11:51 matplotlib-animation.ipynb
